translationContexts: [common, results, state_of_css, state_of_css_2020]
socialMediaImage: stateofcss2020-socialmedia.png
siteTitle: The State of CSS 2020
emailOctopusUrl: https://emailoctopus.com/lists/463dc2a9-b2ff-11e8-a3c9-06b79b628af2/members/embedded/1.3/add
emailOctopusSiteKey: 6LdYsmsUAAAAAPXVTt-ovRsPIJ_IVhvYBBhGvRV6
emailOctopusCode: hp463dc2a9-b2ff-11e8-a3c9-06b79b628af2
