surveyType: state_of_css

currentYear: 2020

allFeatures:
    - grid
    - subgrid
    - flexbox
    - multi_column
    - writing_modes
    - exclusions
    - position_sticky
    - logical_properties
    - aspect_ratio
    - content_visibility

    - shapes
    - object_fit
    - clip_path
    - masks
    - blend_modes
    - filter_effects
    - backdrop_filter

    - scroll_snap
    - overscroll_behavior
    - overflow_anchor
    - touch_action
    - pointer_events

    - web_fonts
    # - variables_fonts
    - line_breaking
    - font_variant
    - initial_letter
    - font_variant_numeric
    - font_display
    - line_clamp
    - direction

    - transitions
    - transforms
    - animations
    - perspective

    - prefers_reduced_motion
    - prefers_color_scheme
    - color_gamut

    - variables
    - feature_support_queries
    - containment
    - will_change
    - calc
    - houdini
    - comparison_functions

featuresCategories:
    layout:
        - grid
        - subgrid
        - flexbox
        - multi_column
        - writing_modes
        - exclusions
        - position_sticky
        - logical_properties
        - aspect_ratio
        - content_visibility
    shapes_and_graphics:
        - shapes
        - object_fit
        - clip_path
        - masks
        - blend_modes
        - filter_effects
        - backdrop_filter
    interactions:
        - scroll_snap
        - overscroll_behavior
        - overflow_anchor
        - touch_action
        - pointer_events
    typography:
        - web_fonts
        # - variables_fonts
        - line_breaking
        - font_variant
        - initial_letter
        - font_variant_numeric
        - font_display
        - line_clamp
        - direction
    animations_and_transforms:
        - transitions
        - transforms
        - animations
        - perspective
    media_queries:
        - prefers_reduced_motion
        - prefers_color_scheme
        - color_gamut
    other_features:
        - variables
        - feature_support_queries
        - containment
        - will_change
        - calc
        - houdini
        - comparison_functions

toolsCategories:
    pre_post_processors:
        - sass
        - less
        - post_css
        - stylus
    css_frameworks:
        - bootstrap
        - materialize_css
        - ant_design
        - semantic_ui
        - bulma
        - foundation
        - ui_kit
        - tachyons
        - primer
        - tailwind_css
        - pure_css
        - skeleton
        - spectre
    css_methodologies:
        - bem
        - atomic_css
        - oocss
        - smacss
        - it_css
        - cube_css
    css_in_js:
        - styled_components
        - jss
        - styled_jsx
        - radium
        - emotion
        - css_modules
        - styled_system
        - stitches
        - styletron
        - fela
        - linaria
        - astroturf
