surveyType: css

currentYear: 2019

featuresCategories:
    layout:
        - grid
        - flexbox
        - multi_column
        - writing_modes
        - exclusions
    shapes_and_graphics:
        - shapes
        - object_fit
        - clip_path
        - masks
        - blend_modes
        - filter_effects
    interactions:
        - scroll_snap
        - overscroll_behavior
        - overflow_anchor
    typography:
        - web_fonts
        - variables_fonts
        - line_breaking
        - font_variant
        - initial_letter
    animations_and_transforms:
        - transitions
        - transforms
        - animations
    other_features:
        - variables
        - feature_support_queries
        - containment
        - will_change
        - calc

toolsCategories:
    pre_post_processors:
        - sass
        - less
        - postcss
        - stylus
    css_frameworks:
        - bootstrap
        - materialize
        - ant_design
        - semanticui
        - bulma
        - foundation
        - uikit
        - tachyons
        - primer
        - tailwind
        - purecss
        - skeleton
        - spectre
    css_methodologies:
        - bem
        - atomic_design
        - css
    css_in_js:
        - styled_components
        - glamor
        - aphrodite
        - jss
        - styled_jsx
        - radium
        - emotion
        - cssmodules
