surveyType: state_of_css

currentYear: 2019

featuresCategories:
    layout:
        - grid
        - flexbox
        - multi_column
        - writing_modes
        - exclusions
    shapes_and_graphics:
        - shapes
        - object_fit
        - clip_path
        - masks
        - blend_modes
        - filter_effects
    interactions:
        - scroll_snap
        - overscroll_behavior
        - overflow_anchor
    typography:
        - web_fonts
        - variables_fonts
        - line_breaking
        - font_variant
        - initial_letter
    animations_and_transforms:
        - transitions
        - transforms
        - animations
    other_features:
        - variables
        - feature_support_queries
        - containment
        - will_change
        - calc

toolsCategories:
    pre_post_processors:
        - sass
        - less
        - post_css
        - stylus
    css_frameworks:
        - bootstrap
        - materialize_css
        - ant_design
        - semantic_ui
        - bulma
        - foundation
        - ui_kit
        - tachyons
        - primer
        - tailwind_css
        - pure_css
        - skeleton
        - spectre
    css_methodologies:
        - bem
        - atomic_css
        - oocss
        - smacss
        - it_css
        - cube_css
    css_in_js:
        - styled_components
        - jss
        - styled_jsx
        - radium
        - emotion
        - css_modules
        - styled_system
        - stitches
        - styletron
        - fela
        - linaria
        - astroturf
